version: '3.5'  

services: 
   backend: 
      image: backend
      build: ./example-backend
      ports: 
        - 8080:8080
      links:
        - redis
        - postgres
      depends_on:
        - redis
        - postgres
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - DB_USERNAME=postgres
        - DB_HOST=postgres
        - DB_NAME=postgres1
      networks:
        - my-net
        
   postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./database:/var/lib/postgresql/data/
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres1
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PGDATA=/var/lib/postgresql/data
      networks:
        - my-net
        
   frontend:
      image: frontend
      build: ./example-frontend
      ports:
        - 5000:5000
      links:
        - redis
      networks:
        - my-net
        
   redis:
      image: redis
      ports:
        - 6379:6379
      networks:
        - my-net
        
   nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      depends_on:
        - backend
        - frontend
      ports:
        - 80:80
      networks:
        - my-net
        
networks:
   my-net:
