version: '3'  

services: 
    
   backend: 
      image: backend
      build: ./example-backend
      ports: 
        - 8080:8080
      links:
        - redis
        - postgres
      depends_on:
        - redis
        - postgres
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - DB_USERNAME=postgres
        - DB_HOST=postgres
        - DB_NAME=postgres1
           
   frontend:
      image: frontend
      build: ./example-frontend
      ports:
        - 5000:5000
      links:
        - redis
        
   postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./database:/var/lib/postgresql/data/
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres1
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PGDATA=/var/lib/postgresql/data
        
   redis:
      image: redis
      ports:
        - 6379:6379

