version: '3.5'  

services: 
   backend: 
      image: backend
      build: ./example-backend
      ports: 
        - 8080:8080
        
   frontend:
      image: frontend
      build: ./example-frontend
      ports:
        - 5000:5000
