version: '3.5'  

services: 
   backend: 
      image: backend
      build: .
      ports: 
        - 8080:8080
        
   frontend:
      image: frontend
      build: .
      ports:
        - 5000:5000
