version: '3.5'  

services: 
   backend: 
      image: backend
      build: ./example-backend
      ports: 
        - 8080:8080
      links:
        - redis
        - postgres
      depends_on:
        - redis
        - postgres
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
      networks:
        - my-net
        
   postgres:
      image: postgres
      restart: always
      environment:
         - POSTGRES_PASSWORD=postgres
      networks:
        - my-net
        
   frontend:
      image: frontend
      build: ./example-frontend
      ports:
        - 5000:5000
      links:
        - redis
      networks:
        - my-net
        
   redis:
      image: redis
      ports:
        - 6379:6379
      networks:
        - my-net
        
   nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      depends_on:
        - backend
        - frontend
      ports:
        - 80:80
      networks:
        - my-net
        
networks:
   my-net:
